# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package
# 触发工作流程的事件
on:
  push:
    branches:
      - main
      - "releases/**"
      - test
      - master
# 按顺序运行作业
jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      -  uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install pnpm
        run: npm install -g pnpm   
      - name: Install dependencies
        run:  pnpm recursive install
      - name: Install semver
        run: pnpm install -g semver 

      # - name: Update Package Versions
      #   run: |
      #     # 获取所有子包的路径
      #     packages=$(find . -name "package.json" -not -path "*/node_modules/*")

      #     # 遍历每个子包，更新版本号
      #     for package in $packages; do
      #       # 获取当前包的版本号
      #       current_version=$(jq -r '.version' $package)

      #       # 增加版本号
      #       updated_version=$(node -p "require('semver').inc('$current_version', 'patch')")
            
      #       # 更新版本号到 package.json 文件
      #       jq --arg updated_version "$updated_version" '.version = $updated_version' $package > tmpfile
      #       mv tmpfile $package
      #     done

      - name: Build package
        run:  pnpm recursive run build

      - name: Publish package to npm
        run: pnpm recursive publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.lemon_test1111 }}
